#define HTML "Content-Type: text/html\r\n"
#define TXT  "Content-Type: text/plain\r\n"
#define JPG  "Content-Type: image/jpeg\r\n"
#define PNG  "Content-Type: image/png\r\n"
#define PDF  "Content-Type: application/pdf\r\n"
#define BIN  "Content-Type: application/octet-stream\r\n"

#define SUCCESS               "HTTP/1.1 200 OK\r\n"
#define CONNECTION_KEEP_ALIVE "Connection: keep-alive\r\n"
#define CONNECTION_CLOSE      "Connection: close\r\n"
#define SERVER                "Server: Alex/Gordon/1.1 (UCLA)\r\n"
